### ISSUE TITLE
Add clang extra tools 

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/clangdev-feedstock#10]
I'm interested in having clang-tidy from the extra tools. After looking through the [debian](https://anonscm.debian.org/viewvc/pkg-llvm/llvm-defaults/trunk/debian/)/[arch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/llvm)/[fedora packages](http://pkgs.fedoraproject.org/cgit/rpms/clang.git/tree/clang.spec) I assume that this can only be build at the same time as clang is build. But for that the recipe would need to download additional sources [clang-tools-extra](http://releases.llvm.org/download.html#4.0.0).

I haven't found anything in the official docs how to add more then one source to a conda-recipe. I found a working [example](https://github.com/stuarteberg/conda-multisrc-example). It basically adds a new sources section in extra.

**Comment by kain88-de** [comment]
The example I link to doesn't work with the current version of conda build anymore.

**Comment by inducer** [comment]
We're already fairly limited by the time cutoffs of the CIs, so adding anything to the build process is a big ask.

**Comment by jakirkham** [comment]
Would it be possible to build this as a separate package that depends on `clangdev`, @kain88-de? It might be worth trying in any case to see if it just works. Seems like that would be the best way to unblock this. Otherwise we are at the mercy of the CIs and what time they allow us.

**Comment by saraedum** [comment]
@jakirkham I don't understand the details but it seems that you need to build `clang-tidy` and such at the time your building clang from this SO post https://stackoverflow.com/questions/47255526/how-to-build-the-latest-clang-tidy.
So it would be an additional output of the same recipe I guess.
@inducer do you think that building these tools would add much to clang's build time?

**Comment by isuruf** [comment]
@saraedum, we have enough time to build extra tools as we've switched to azure
