### ISSUE TITLE
Accidentally built cling packages

### ISSUE THREAD

**Issue by inducer** [conda-forge/clangdev-feedstock#12]
@SylvainCorlay Looks like 4.0.0 cling-variant packages [got built](https://anaconda.org/conda-forge/clangdev/files) after all--although I'm not sure why. I thought I [disabled](https://github.com/conda-forge/clangdev-feedstock/pull/11/files#diff-c48034b662d2a516a39beb01e6a756dfR2) them. Could you help assess the damage? Sorry about this.

**Comment by SylvainCorlay** [comment]
Sorry, I had completely missed this.
This was probably a rerendering issue. This should be all fixed with the new compiler transition.
