### ISSUE TITLE
Flang patches

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/clangdev-feedstock#13]
To build flang, it seems one needs a patched copy of [clang]( https://github.com/flang-compiler/clang ), which the flang developers provide. Would be interesting if we could add these patches here somehow, but am not entirely sure the right way to do this given there are no formal releases of either.

**Comment by jakirkham** [comment]
From your experimentation with flang, do you have a good idea as to what patches will be needed here, @isuruf?

**Comment by isuruf** [comment]
The patches don't interfere with the C, C++ modes of clang and it's okay I guess to patch the default build. But since there's no release we'll have to have a different version name.

**Comment by isuruf** [comment]
Patches are maintained for 3.9.1, 4.0.1 and 5.0.0
