### ISSUE TITLE
Moving files instead of copying them to save space

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/clangdev-feedstock#132]
https://github.com/conda-forge/clangdev-feedstock/blob/b5eea1e32c5118ea572e21e22a1f91e2c7a3cd90/recipe/install_libclang.sh#L10

I'm going through a size audit of a package of mine and noticed that the `libclang.so` and `libclang.so.10` are actully two seperate files and not symlinks.

Would it be acceptable if I made a PR for one to be a symlink to an other?

**Comment by isuruf** [comment]
Sure
