### ISSUE TITLE
Towards packaging cling 0.9: cling variant of clangdev 9.x

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/clangdev-feedstock#144]
Cling 0.9, which was released a few months ago requires clangdev 9.x, which the previous versions were using clangdev 5.x.

Unfortunately, both versions require a clangdev variant including some patches. There is a similar set of patches for the clangdev variant required for thr root project

For the [5.x version](https://github.com/conda-forge/clangdev-feedstock/tree/5.x/recipe), we were using the root-project git fork of clangdev to get a version of clang that was requiring these patches, while for 9.x, [the patches are included in the recipe](https://github.com/conda-forge/clangdev-feedstock/tree/9.x/recipe).

@chrisburr what do you think is the best approach here? Is there a reason why we now include the root patches instead of using their fork?

**Comment by saraedum** [comment]
@SylvainCorlay isn't the result of this that we cannot install cling and the root clangdev at the same time anymore? As a consequence, we can not install cppyy and cling at the same time anymore.
clangdev 9 with the root patches works nicely for cppyy (which essentially builds its own cling in the cppyy-cling-feedstock.) Maybe the root patches also work again for cling 0.9?

**Comment by SylvainCorlay** [comment]
Closing as the variant is now available.
