### ISSUE TITLE
Dependencies needed by clang-tools

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/clangdev-feedstock#147]
After doing a bit of digging into an issue recently, we noticed that `clang-tools` is depending on [a few things]( https://github.com/conda-forge/clangdev-feedstock/blob/83cefdc6bfd937aa14138cf601945c6d9fc9a490/recipe/meta.yaml#L313-L316 ), which may not always be needed (or at least it wasn't clear they would be after doing some initial exploration. In particular a [recent CI log]( https://github.com/conda-forge/clangdev-feedstock/files/6889251/linux_64_variantdefault_20210709_5.txt ) (comes from [this build]( https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/349672/logs/35 )) seems to indicate `libclang-cpp` (in this case `libclang-cpp12`), `libLLVM` (in this case `libLLVM-12`), and the usual GCC and system libraries. Given this, it seems like it should be possible to cutdown the dependencies of `clang-tools` to this shortened list. Have not looked into other packages, but this may be the case elsewhere as well. Though please correct me if there are things we are overlooking here

cc @robertmaynard @dantegd

**Comment by henryiii** [comment]
Currently running into the problem that the new conda support for pre-commit.ci is limited to 250MB and clang-tools is 623.1 MB - maybe this would help? Do you know how much it might? If not, could just the clang-format and required dependencies part be pulled off into a package that could be installed by itself? (that is, do you think it might be small enough to make it work a try).

**Comment by henryiii** [comment]
build of local:--channel=conda-forge,clang-tools==12.0.1@1 for conda@default exceeds tier max size 250MiB: 307MiB

No!!! So close!!!! (Was 650 MB)

**Comment by isuruf** [comment]
It's 144MB for me. Maybe they are not deleting the tarballs.

**Comment by henryiii** [comment]
Is there a way to tell it to prune those when installing? I'm guessing it's in this part: https://github.com/pre-commit/pre-commit/blob/2ef29b7f95384f899ede86a370bf2a1c766095b4/pre_commit/languages/conda.py#L63-L71 that you could delete the tarballs that get downloaded, perhaps?

**Comment by henryiii** [comment]
`conda clean --tarballs` right afterwards?

**Comment by isuruf** [comment]
you can call `conda clean -tip` afterwards

**Comment by henryiii** [comment]
To me it looks like it's only capturing the environment directory. When I try it locally, I get a `conda-default` directory produced by pre-commit of 232M; less than the reported size (and actually should have just slipped in under the limit, so not sure where the extra size is).

For sizes, three executables take up pretty much the whole 50MB bin directory, clang-tidy, clangd, and c-index-test. The rest of the size seems to be in lib, in pretty obvious libs (libLLVM-12.dylib, libclang-cpp.12.dylib, libclang.12.dylib).

**Comment by isuruf** [comment]
Only `c-index-test` need `libclang.12.dylib`.

**Comment by henryiii** [comment]
Yes, here are the sizes over 1MB:

```
bin:
35M	c-index-test
18M	clangd
11M	clang-tidy
1.3M	clang-doc
...

lib:
110M	../lib/libLLVM-12.so
70M	../lib/libclang-cpp.so.12
36M	../lib/libclang.so.12
12M	../lib/libstdc++.so.6.0.29
3.2M	../lib/libcrypto.so.1.1
...
```

Not seeing much that can be stripped there. If clang-tidy was pulled out, we could save a bit in bin, but likely not much/any in lib. Hmm, though, actually lib totals to 234M.

Oh, if we could drop libclang + c-index-test, that would be big.

**Comment by isuruf** [comment]
I suggest creating a new package `clang-format-12` that has just `clang-format-12` that would depend on just `libllvm-12` and `libclang-cpp-12`.

**Comment by henryiii** [comment]
Does the build portion of clang-tools have to be duplicated or can files be picked/filtered out? I'm guessing this would be in this repo, just another package output?

**Comment by isuruf** [comment]
You can pick files using https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/blob/master/recipe/meta.yaml#L215-L216
