### ISSUE TITLE
Is llvmdev needed at runtime?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/clangdev-feedstock#16]
LLVM libraries are linked in statically, so they are not needed unless I'm missing something.

**Comment by jakirkham** [comment]
You're right. I don't think they should be. Can do a quick check with `conda inspect linkages` though.

**Comment by jakirkham** [comment]
Would you like to try submitting a PR?

**Comment by isuruf** [comment]
`llvmdev` is needed for the headers of `clangdev`. So, I'm going to close this as a duplicate of https://github.com/conda-forge/clangdev-feedstock/issues/15
