### ISSUE TITLE
Libclang so version different than version

### ISSUE THREAD

**Issue by adam-urbanczyk** [conda-forge/clangdev-feedstock#195]
### Comment:

Even for say llvm 15 the version of libclang is hardcoded to 13:

https://github.com/conda-forge/clangdev-feedstock/blob/b6cf7124da893bcb57ab1f38c768ea825fabbdb1/recipe/meta.yaml#L11

Is this intentional? What does `libclang-13.dll` version `15` actually mean?

**Comment by adam-urbanczyk** [comment]
Found the answer here:

https://github.com/conda-forge/clangdev-feedstock/blob/b6cf7124da893bcb57ab1f38c768ea825fabbdb1/recipe/conda_build_config.yaml#L6

Maybe good to add this comment to the meta.yaml too. `abiversion` would be less confusing than `soversion`. Closing otherwise.

**Comment by h-vetinari** [comment]
> Maybe good to add this comment to the meta.yaml too. `abiversion` would be less confusing than `soversion`. Closing otherwise.

I find soversion more accurate (and it's also the name of this variable in cmake). Strictly speaking, the ABI can still change in non-breaking ways, i.e. symbols can be added without having to bump the (abi)version.

**Comment by adam-urbanczyk** [comment]
Thanks for the clarifications (and indeed CMake does use this convention https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html )!
