### ISSUE TITLE
clang binaries breaking with new windows-2022 image

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/clangdev-feedstock#202]
With the recent release of conda-smithy containing https://github.com/conda-forge/conda-smithy/pull/1720, I now get:
```
ninja -j2 
ninja: error: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/DIA SDK/lib/amd64/diaguids.lib', needed by 'bin/clang-ast-dump.exe', missing and no known rule to make it
```
in #201, and same for [mlir](https://github.com/conda-forge/mlir-feedstock/pull/37) & [lld](https://github.com/conda-forge/lld-feedstock/pull/54) (always about `diaguids.lib`), though not [openmp](https://github.com/conda-forge/openmp-feedstock/pull/79). It's possible to fix it by downgrading the image back to `windows-2019`, which I'm doing for now.

I assume other feedstocks will soon run into these issues as well.

It seems to me like a quick fix would be rebuilding clang 14 on the `windows-2022` image, but better would be of course to not depend on that library at all.

CC @conda-forge/core

**Comment by hmaarrfk** [comment]
I think i just hit this trying to build qt6.

**Comment by isuruf** [comment]
Option 3 would be to patch the cmake file and replace `C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/` with `%VSINSTALLDIR%`

**Comment by h-vetinari** [comment]
> Option 3 would be to patch the cmake file and replace `C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/` with `%VSINSTALLDIR%`

I chased this down to [`llvmdev`](https://github.com/regro/libcfgraph/blob/master/artifacts/llvmdev/conda-forge/win-64/llvmdev-14.0.6-h97333cc_1.json#L2194), and some upstream code that uses `VSINSTALLERDIR` (note extra "ER"). PR attempt in https://github.com/conda-forge/llvmdev-feedstock/pull/199

**Comment by h-vetinari** [comment]
Should be fixed by https://github.com/conda-forge/llvmdev-feedstock/pull/199 & https://github.com/conda-forge/llvmdev-feedstock/pull/216
