### ISSUE TITLE
Add a new branch for the flang variant

### ISSUE THREAD

**Issue by xoviat** [conda-forge/clangdev-feedstock#23]
/cc @inducer 

Would you mind creating a new branch called "flang" so that I can file a PR against it? We're currently blocked on adding flang to the feedstocks.

**Comment by inducer** [comment]
Not sure I understand the full context here. What would this allow you to do that you couldn't by cloning this repo and creating a pull request?

**Comment by xoviat** [comment]
I can only file a pull request against branches that exist. @isuruf wants me to put flang in a separate branch.

**Comment by xoviat** [comment]
See this comment: https://github.com/conda-forge/clangdev-feedstock/pull/19#issuecomment-341870635

**Comment by xoviat** [comment]
Shall I file against master?

**Comment by inducer** [comment]
https://github.com/conda-forge/clangdev-feedstock/tree/flang
