### ISSUE TITLE
Summary of Package Contents

### ISSUE THREAD

**Issue by phreed** [conda-forge/clangdev-feedstock#233]
### Comment:

Please provide a brief summary expressing what is in the various packages.
I am developing a `clang` plugin to extract information from the AST.
In particular, I need the clang headers.
```cpp
// tag::visitor_hdr[]
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Tooling/CommonOptionsParser.h"
#include "clang/Tooling/Tooling.h"
// end::visitor_hdr[]
```
Are these present in any of the packages?

**Comment by phreed** [comment]
I want to consume these files via `cmake`.
To that end, https://llvm.org/docs/CMake.html , https://cmake.org/cmake/help/latest/command/find_package.html , and https://github.com/banach-space/clang-tutor look relevant.

```powershell
$mambaInfo = mamba info --json | ConvertFrom-Json
Get-ChildItem -path $mambaInfo.'env location' -Filter 'LLVMConfig.cmake' -Recurse -ErrorAction SilentlyContinue -Force
```

```text
Directory: C:\Users\<self>\micromamba\envs\<proj>\lib\cmake\llvm
Name: LLVMConfig.cmake
```
I presume there is some environment variable which needs to be set for the `find_package( LLVM ... ` to work correctly.

**Comment by h-vetinari** [comment]
> I want to consume these files via `cmake`.

llvm has a shared cmake infastructure, which doesn't necessarily match with the way we need to split our packaging (not least due to the 6h timeout imposed by CI). So it's possible you need _both_ `llvmdev` and `clangdev`

**Comment by h-vetinari** [comment]
Closing this as answered
