### ISSUE TITLE
BUG: clangxx contains `bin/-clang++`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/clangdev-feedstock#239]
This is supposed to be `$HOST-clang++`, but AFAICT from looking at the package contents of `clangxx`, this has never worked since it was introduced in https://github.com/conda-forge/clangdev-feedstock/commit/7c4cd24a29cbd491d8b3566d98708fb350109a3a, apparently because `$HOST` is empty in `install_clangxx.sh`.

Looking how this is [done](https://github.com/conda-forge/ctng-compilers-feedstock/blob/923b25fa711bd71cc7c43299e032bd87579dbce9/recipe/install-g%2B%2B.sh#L3) for gcc, the triple is constructed explicitly (with some content templated in `conda_build_config.yaml`). Same [story](https://github.com/conda-forge/clang-win-activation-feedstock/blob/840f4cb151e8116012bada87ec8bb8805eb523e3/recipe/install-pkg.sh#L42) for clang on windows.

We could fix the triple, but OTOH, it's pretty obvious that no-one has ever used that symlink. So why not just remove it?

CC @isuruf

**Comment by h-vetinari** [comment]
This is still an issue as of clang 17, c.f. package [contents](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fclangxx-17.0.2-default_h1cdf331_0.conda):
```
bin/-clang++
bin/clang++
```

@isuruf, WDYT about removing the symlink entirely (it's obviously unused)? Or would you prefer adding a proper `$HOST` triple?

**Comment by isuruf** [comment]
Yes, that can be removed from this feedstock.
