### ISSUE TITLE
Variant selection is fragile

### ISSUE THREAD

**Issue by isuruf** [conda-forge/clangdev-feedstock#24]
The two variants `default` and `cling` have build strings like `default_0` and `cling_0` for build number 0.
As far as I understand the `conda` solver will choose `default_0` because alphabetically it comes after `cling_0` and therefore considers `default_0` a newer version than `cling_0`. 

Problem is that if I add `flang` as a variant `conda` solver will consider that the latest version as `flang` comes after `default`.

cc @SylvainCorlay, @jakirkham

**Comment by xoviat** [comment]
Is this a blocker?

**Comment by SylvainCorlay** [comment]
My understanding is that since the cling variant requires the `cling-patches` feature, this variant cannot be installed if a package tracking that feature is not installed, so I don't think that the alphabetical order plays a role at all.

**Comment by isuruf** [comment]
You are right.
