### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/clangdev-feedstock#3]
Do we currently provide OpenMP support? Are we testing for it? If not, could we?

**Comment by inducer** [comment]
Don't believe we do. A minimum requirement would probably be to pull in the OMP runtime: http://releases.llvm.org/download.html#3.9.1

Not sure how much is needed beyond just adding that, or if that needs to be there at build time/before/after.

**Comment by yesimon** [comment]
I believe compilation of the OpenMP component requires the base llvm compilation directives. In this recipe, the `cfe` package is built directly versus as a component within an llvm build. @inducer any insights as to the differences between these cases?

**Comment by inducer** [comment]
The goal (as far as I am concerned) was to allow packages to depend on llvm without automatically dragging along all of clang.

**Comment by jakirkham** [comment]
Do you have a patch that you could share, @yesimon? It would be interesting to push on this a bit.

**Comment by yesimon** [comment]
See https://github.com/conda-forge/staged-recipes/pull/3171

**Comment by jakirkham** [comment]
Based on the work done in the aforementioned PR and associated testing, we can be fairly confident that there is no need to rebuild `clangdev` or `llvmdev` to handle `openmp`'s requirements. It seems like simply having `openmp` installed alongside `clangdev` is sufficient to build working OpenMP code into binaries using OpenMP.

**Comment by jakirkham** [comment]
FTR `openmp` is now a feedstock with packages built and available for all OSes.
