### ISSUE TITLE
Drop Windows xz dependency

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/clangdev-feedstock#31]
Would be good to drop [both `m2-xz` and `m2w64-xz`]( https://github.com/conda-forge/clangdev-feedstock/blob/3ff4dd4957860f438bc62967c32be8798e4ce0e6/recipe/meta.yaml#L100-L101 ) as `python 2.7.*` is skipped.

**Comment by isuruf** [comment]
Done

**Comment by jakirkham** [comment]
Thanks :)
