### ISSUE TITLE
CUDA is not clang 9+ ready.

### ISSUE THREAD

**Issue by pearu** [conda-forge/clangdev-feedstock#76]
Issue:

When using `clang` as a compiler, the following error is raised:
```
In file included from /usr/local/cuda-10.1.243/bin/../targets/x86_64-linux/include/cuda_runtime.h:83:
/usr/local/cuda-10.1.243/bin/../targets/x86_64-linux/include/crt/host_config.h:146:2: error: -- unsupported clang version! clang version must be less than 9 and greater than 3.2
#error -- unsupported clang version! clang version must be less than 9 and greater than 3.2
```

Would it be possible to continue supporting clangdev 8 conda package?

**Comment by milljm** [comment]
You should be able to grab any version listed with:

`conda search clangdev`

For your particular issue, `conda install clangdev=8`

**Comment by pearu** [comment]
Sure. However, this issue is raised for a different reason. Note that the `clangdev` package (that currently is based on clang version 9) is updated whenever its dependencies are updated.
However, the `clangdev=8` package is not be updated when its dependencies are updated.

This issue is about asking for updates of the `clangdev=8` package whenever its dependencies are updated. I am not sure that is the recommended way to do it, introducing `clangdev8`?

**Comment by jakirkham** [comment]
Could you please provide an MRE? I'm not entirely clear the context in which this is occurring currently.

cc @kkraus14

**Comment by pearu** [comment]
@jakirkham 
The current CUDA libraries (versions 10.2.89 and earlier) do not support clang>=9.

So, when using clang 9 (that the current clangdev provides) as the C/C++ compiler in a project that depends on a CUDA library, the build will fail with the message shown in the description.

This issue was reported when omniscidb-cuda-feedstock used clang as the C/C++ compiler. It does not anymore mostly because of this issue. However, this issue remains a problem for other CUDA dependent projects that do need/want to use clang as the compiler (read: then these projects cannot use the latest clangdev providing clang>=9).

**Comment by jakirkham** [comment]
Is it that we care about Clang 8.0.0 or 8.0.1?

**Comment by pearu** [comment]
> Is it that we care about Clang 8.0.0 or 8.0.1?

8.0.1 (as I don't know the reasons why 8.0.0 would be preferred).

**Comment by isuruf** [comment]
If you want updates to clang 8.0.1, please send a PR. I don't know what updates you want though.
