### ISSUE TITLE
Status of aarch64 and ppc64le?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/clangdev-feedstock#78]
The builds were added in #52 (where they had to be built manually) and then removed in https://github.com/conda-forge/clangdev-feedstock/commit/c25a9c7420f909007c06b605eb67a56da0c158dc as part of #53.

What's the current status on this? It seems to be "only" a question of CI limits? In other words the builds could be added manually? In that case it would be a case for conda-forge/conda-forge-enhancement-proposals#5 (and possibly conda-forge/conda-forge.github.io#902).

**Comment by jakirkham** [comment]
cc @conda-forge/arm-arch

**Comment by hmaarrfk** [comment]
I think this requires somebody to type build locally on a computer they can leave on for a few days.

**Comment by h-vetinari** [comment]
Any linked issue/PR or reason for closing?

**Comment by isuruf** [comment]
https://anaconda.org/conda-forge/clangdev/files?version=9.0.1

**Comment by h-vetinari** [comment]
Cool, thanks.

**Comment by h-vetinari** [comment]
At first I ignored what looked like a generic migration-commit, but https://github.com/conda-forge/clangdev-feedstock/commit/088b971943cc4149a456444d817fa5b9b23e4fda answers how this happened. :)
